### ISSUE TITLE
[EPIC] Add new type / update <type-name> in source connector <connector-name>

### ISSUE THREAD

**Issue by georgesequeira** [AxonHQ/airbyte#1]
## Summary
(Choose one of the two below.)
- [ ] Support new type <type-name>
- [ ] Update existing type <type-name>

## TODOs
(Complete the TODOs based on the instruction, and convert each bullet point with the `[Issue]` tag into an issue.)
- [ ] [Issue] Add a new destination acceptance test (DAT) test case for this type.
- List every destination below, either update the destination to suppor this type, or override its DAT to bypass the new test case.
  - [ ] Example: [Issue] support <type-name> in destination bigquery
- [ ] [Issue] Make sure every destination can pass the new DAT test case.
  - Even if a destination does not need to support this type, its DAT should not break.
- List every source that should support this type below.
  - [ ] Example: [Issue] support <type-name> in source github
